// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

fn main() {

    let mut term1 = 1;
    let mut term2 = 2;
    let mut holder;
    let mut sum = 0;

    // Continue until term
    while term2 < 4000000 {

        // sum even valued terms
        if term1 % 2 == 0 {
            sum += term1;
        }
        holder = term1 + term2;
        term1 = term2;
        term2 = holder;
    }

    // Take into account last term
    if term2 % 2 == 0 {
        sum += term2;
    }

    if term1 % 2 == 0 {
        sum += term1;
    }

    println!("The answer is {}", sum);
}
