[package]
name = "dayone"
version = "0.1.0"
authors = ["Vanessa Sochat <vsochat@stanford.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math = "0.0.2"
